Compiled from "PluginAssertionFailure.java"
public class org.apache.commons.digester.plugins.PluginAssertionFailure extends java.lang.RuntimeException {
  private java.lang.Throwable cause;

  public org.apache.commons.digester.plugins.PluginAssertionFailure(java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: invokevirtual #1                  // Method java/lang/Throwable.getMessage:()Ljava/lang/String;
       5: invokespecial #2                  // Method "<init>":(Ljava/lang/String;)V
       8: aload_0
       9: aload_1
      10: putfield      #3                  // Field cause:Ljava/lang/Throwable;
      13: return

  public org.apache.commons.digester.plugins.PluginAssertionFailure(java.lang.String);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #4                  // Method java/lang/RuntimeException."<init>":(Ljava/lang/String;)V
       5: aload_0
       6: aconst_null
       7: putfield      #3                  // Field cause:Ljava/lang/Throwable;
      10: return

  public org.apache.commons.digester.plugins.PluginAssertionFailure(java.lang.String, java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #2                  // Method "<init>":(Ljava/lang/String;)V
       5: aload_0
       6: aload_2
       7: putfield      #3                  // Field cause:Ljava/lang/Throwable;
      10: return

  public java.lang.Throwable getCause();
    Code:
       0: aload_0
       1: getfield      #3                  // Field cause:Ljava/lang/Throwable;
       4: areturn
}
