Compiled from "PGXAException.java"
public class org.postgresql.xa.PGXAException extends javax.transaction.xa.XAException {
  org.postgresql.xa.PGXAException(java.lang.String, int);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #1                  // Method javax/transaction/xa/XAException."<init>":(Ljava/lang/String;)V
       5: aload_0
       6: iload_2
       7: putfield      #2                  // Field errorCode:I
      10: return

  org.postgresql.xa.PGXAException(java.lang.String, java.lang.Throwable, int);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #1                  // Method javax/transaction/xa/XAException."<init>":(Ljava/lang/String;)V
       5: aload_0
       6: aload_2
       7: invokevirtual #3                  // Method initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      10: pop
      11: aload_0
      12: iload_3
      13: putfield      #2                  // Field errorCode:I
      16: return

  org.postgresql.xa.PGXAException(java.lang.Throwable, int);
    Code:
       0: aload_0
       1: iload_2
       2: invokespecial #4                  // Method javax/transaction/xa/XAException."<init>":(I)V
       5: aload_0
       6: aload_1
       7: invokevirtual #3                  // Method initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      10: pop
      11: return
}
