Compiled from "ListenableFutureAdapter.java"
class org.springframework.util.concurrent.ListenableFutureAdapter$1 implements org.springframework.util.concurrent.ListenableFutureCallback<S> {
  final org.springframework.util.concurrent.SuccessCallback val$successCallback;

  final org.springframework.util.concurrent.FailureCallback val$failureCallback;

  final org.springframework.util.concurrent.ListenableFutureAdapter this$0;

  org.springframework.util.concurrent.ListenableFutureAdapter$1(org.springframework.util.concurrent.ListenableFutureAdapter, org.springframework.util.concurrent.SuccessCallback, org.springframework.util.concurrent.FailureCallback);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field this$0:Lorg/springframework/util/concurrent/ListenableFutureAdapter;
       5: aload_0
       6: aload_2
       7: putfield      #2                  // Field val$successCallback:Lorg/springframework/util/concurrent/SuccessCallback;
      10: aload_0
      11: aload_3
      12: putfield      #3                  // Field val$failureCallback:Lorg/springframework/util/concurrent/FailureCallback;
      15: aload_0
      16: invokespecial #4                  // Method java/lang/Object."<init>":()V
      19: return

  public void onSuccess(S);
    Code:
       0: aload_0
       1: getfield      #1                  // Field this$0:Lorg/springframework/util/concurrent/ListenableFutureAdapter;
       4: aload_1
       5: invokevirtual #5                  // Method org/springframework/util/concurrent/ListenableFutureAdapter.adaptInternal:(Ljava/lang/Object;)Ljava/lang/Object;
       8: astore_2
       9: goto          42
      12: astore_3
      13: aload_3
      14: invokevirtual #7                  // Method java/util/concurrent/ExecutionException.getCause:()Ljava/lang/Throwable;
      17: astore        4
      19: aload_0
      20: aload         4
      22: ifnull        30
      25: aload         4
      27: goto          31
      30: aload_3
      31: invokevirtual #8                  // Method onFailure:(Ljava/lang/Throwable;)V
      34: return
      35: astore_3
      36: aload_0
      37: aload_3
      38: invokevirtual #8                  // Method onFailure:(Ljava/lang/Throwable;)V
      41: return
      42: aload_0
      43: getfield      #2                  // Field val$successCallback:Lorg/springframework/util/concurrent/SuccessCallback;
      46: aload_2
      47: invokeinterface #10,  2           // InterfaceMethod org/springframework/util/concurrent/SuccessCallback.onSuccess:(Ljava/lang/Object;)V
      52: return
    Exception table:
       from    to  target type
           0     9    12   Class java/util/concurrent/ExecutionException
           0     9    35   Class java/lang/Throwable

  public void onFailure(java.lang.Throwable);
    Code:
       0: aload_0
       1: getfield      #3                  // Field val$failureCallback:Lorg/springframework/util/concurrent/FailureCallback;
       4: aload_1
       5: invokeinterface #11,  2           // InterfaceMethod org/springframework/util/concurrent/FailureCallback.onFailure:(Ljava/lang/Throwable;)V
      10: return
}
