Compiled from "Try.scala"
public final class scala.util.Failure$ implements scala.Serializable {
  public static final scala.util.Failure$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class scala/util/Failure$
       3: invokespecial #14                 // Method "<init>":()V
       6: return

  public final java.lang.String toString();
    Code:
       0: ldc           #18                 // String Failure
       2: areturn

  public <T> scala.util.Failure<T> apply(java.lang.Throwable);
    Code:
       0: new           #23                 // class scala/util/Failure
       3: dup
       4: aload_1
       5: invokespecial #26                 // Method scala/util/Failure."<init>":(Ljava/lang/Throwable;)V
       8: areturn

  public <T> scala.Option<java.lang.Throwable> unapply(scala.util.Failure<T>);
    Code:
       0: aload_1
       1: ifnonnull     10
       4: getstatic     #35                 // Field scala/None$.MODULE$:Lscala/None$;
       7: goto          21
      10: new           #37                 // class scala/Some
      13: dup
      14: aload_1
      15: invokevirtual #40                 // Method scala/util/Failure.exception:()Ljava/lang/Throwable;
      18: invokespecial #43                 // Method scala/Some."<init>":(Ljava/lang/Object;)V
      21: areturn

  private java.lang.Object readResolve();
    Code:
       0: getstatic     #51                 // Field MODULE$:Lscala/util/Failure$;
       3: areturn

  private scala.util.Failure$();
    Code:
       0: aload_0
       1: invokespecial #52                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: putstatic     #51                 // Field MODULE$:Lscala/util/Failure$;
       8: return
}
