Compiled from "ValidatorException.java"
public class org.jboss.jca.validator.ValidatorException extends java.lang.Exception {
  private static final long serialVersionUID;

  private final java.util.Collection<org.jboss.jca.validator.Failure> failures;

  public org.jboss.jca.validator.ValidatorException(java.lang.String, java.util.Collection<org.jboss.jca.validator.Failure>);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #1                  // Method java/lang/Exception."<init>":(Ljava/lang/String;)V
       5: aload_0
       6: aload_2
       7: putfield      #2                  // Field failures:Ljava/util/Collection;
      10: return

  public org.jboss.jca.validator.ValidatorException(java.lang.String, java.util.Collection<org.jboss.jca.validator.Failure>, java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: aload_3
       3: invokespecial #3                  // Method java/lang/Exception."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
       6: aload_0
       7: aload_2
       8: putfield      #2                  // Field failures:Ljava/util/Collection;
      11: return

  public synchronized java.util.Collection<org.jboss.jca.validator.Failure> getFailures();
    Code:
       0: aload_0
       1: getfield      #2                  // Field failures:Ljava/util/Collection;
       4: areturn
}
