Compiled from "Exception.scala"
public final class scala.util.control.Exception$Catch$$anonfun$toOption$1 extends scala.runtime.AbstractFunction1<java.lang.Throwable, scala.None$> implements scala.Serializable {
  public static final long serialVersionUID;

  public final scala.None$ apply(java.lang.Throwable);
    Code:
       0: getstatic     #25                 // Field scala/None$.MODULE$:Lscala/None$;
       3: areturn

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #32                 // class java/lang/Throwable
       5: invokevirtual #34                 // Method apply:(Ljava/lang/Throwable;)Lscala/None$;
       8: areturn

  public scala.util.control.Exception$Catch$$anonfun$toOption$1(scala.util.control.Exception$Catch<T>);
    Code:
       0: aload_0
       1: invokespecial #41                 // Method scala/runtime/AbstractFunction1."<init>":()V
       4: return
}
