Compiled from "ResourceReferenceProcessor.java"
class org.jboss.as.ee.component.deployers.ResourceReferenceProcessor$2 implements org.jboss.as.naming.ManagedReferenceFactory {
  final java.lang.String val$url;

  final org.jboss.as.ee.component.deployers.ResourceReferenceProcessor this$0;

  org.jboss.as.ee.component.deployers.ResourceReferenceProcessor$2(org.jboss.as.ee.component.deployers.ResourceReferenceProcessor, java.lang.String);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #1                  // Field this$0:Lorg/jboss/as/ee/component/deployers/ResourceReferenceProcessor;
       5: aload_0
       6: aload_2
       7: putfield      #2                  // Field val$url:Ljava/lang/String;
      10: aload_0
      11: invokespecial #3                  // Method java/lang/Object."<init>":()V
      14: return

  public org.jboss.as.naming.ManagedReference getReference();
    Code:
       0: new           #4                  // class org/jboss/as/naming/ImmediateManagedReference
       3: dup
       4: new           #5                  // class java/net/URL
       7: dup
       8: aload_0
       9: getfield      #2                  // Field val$url:Ljava/lang/String;
      12: invokespecial #6                  // Method java/net/URL."<init>":(Ljava/lang/String;)V
      15: invokespecial #7                  // Method org/jboss/as/naming/ImmediateManagedReference."<init>":(Ljava/lang/Object;)V
      18: areturn
      19: astore_1
      20: new           #9                  // class java/lang/RuntimeException
      23: dup
      24: aload_1
      25: invokespecial #10                 // Method java/lang/RuntimeException."<init>":(Ljava/lang/Throwable;)V
      28: athrow
    Exception table:
       from    to  target type
           0    18    19   Class java/net/MalformedURLException
}
