Compiled from "Fail.java"
public final class org.assertj.core.api.Fail {
  public static void setRemoveAssertJRelatedElementsFromStackTrace(boolean);
    Code:
       0: invokestatic  #13                 // Method org/assertj/core/internal/Failures.instance:()Lorg/assertj/core/internal/Failures;
       3: iload_0
       4: invokevirtual #15                 // Method org/assertj/core/internal/Failures.setRemoveAssertJRelatedElementsFromStackTrace:(Z)V
       7: return

  public static void fail(java.lang.String);
    Code:
       0: invokestatic  #13                 // Method org/assertj/core/internal/Failures.instance:()Lorg/assertj/core/internal/Failures;
       3: aload_0
       4: invokevirtual #23                 // Method org/assertj/core/internal/Failures.failure:(Ljava/lang/String;)Ljava/lang/AssertionError;
       7: athrow

  public static void fail(java.lang.String, java.lang.Object...);
    Code:
       0: aload_0
       1: aload_1
       2: invokestatic  #32                 // Method java/lang/String.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
       5: invokestatic  #34                 // Method fail:(Ljava/lang/String;)V
       8: return

  public static void fail(java.lang.String, java.lang.Throwable);
    Code:
       0: invokestatic  #13                 // Method org/assertj/core/internal/Failures.instance:()Lorg/assertj/core/internal/Failures;
       3: aload_0
       4: invokevirtual #23                 // Method org/assertj/core/internal/Failures.failure:(Ljava/lang/String;)Ljava/lang/AssertionError;
       7: astore_2
       8: aload_2
       9: aload_1
      10: invokevirtual #43                 // Method java/lang/AssertionError.initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      13: pop
      14: aload_2
      15: athrow

  public static void failBecauseExceptionWasNotThrown(java.lang.Class<? extends java.lang.Throwable>);
    Code:
       0: aload_0
       1: invokestatic  #52                 // Method shouldHaveThrown:(Ljava/lang/Class;)V
       4: return

  public static void shouldHaveThrown(java.lang.Class<? extends java.lang.Throwable>);
    Code:
       0: invokestatic  #13                 // Method org/assertj/core/internal/Failures.instance:()Lorg/assertj/core/internal/Failures;
       3: aload_0
       4: invokevirtual #59                 // Method org/assertj/core/internal/Failures.expectedThrowableNotThrown:(Ljava/lang/Class;)Ljava/lang/AssertionError;
       7: athrow

  protected org.assertj.core.api.Fail();
    Code:
       0: aload_0
       1: invokespecial #63                 // Method java/lang/Object."<init>":()V
       4: return
}
